version: '3.8'

services:
  frontend:
    build: 
      context: .
      target: builder
    container_name: frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    external: true 